name: CI/CD Workflow

on:
  # push:
  #   branches: [ "development" ]
  pull_request:
    branches: [ "Development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build Docker images
      run: docker-compose build
      
    - name: Test Docker containers
      run: docker-compose up -d
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        
    - name: Run get homepage test
      if: github.ref == 'refs/heads/development'
      run: pytest tests/test_homepage.py
  
    - name: Run create user test
      if: github.ref == 'refs/heads/development'
      run: pytest tests/test_user_register.py
      
    - name: Run login test
      if: github.ref == 'refs/heads/development'
      run: pytest tests/test_login.py
      
    - name: Login and get all actions
      if: github.ref == 'refs/heads/development'
      run: pytest tests/test_get_all_actions.py
      
    - name: Create a new action
      if: github.ref == 'refs/heads/development'
      run: pytest tests/test_create_get_delete_specific_action.py
      
    - name: Stop Docker containers
      run: docker-compose down
