name: CI/CD Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build Docker images
      run: docker-compose build
      
    - name: Test Docker containers
      run: docker-compose up -d
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
      # Replace <service-name> with the name of your Python service/container
    - name: Run get homepage test
      run: pytest tests/test_homepage.py
  
    - name: Run create user test
      run: pytest tests/test_user_register.py
      
    - name: Run login test
      run: pytest tests/test_login.py
      
    - name: Login and get all actions
      run: pytest tests/test_get_all_actions.py
      
    - name: Create a new action
      run: pytest tests/test_create_get_delete_specific_action.py
      
    - name: Stop Docker containers
      run: docker-compose down
